spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal_db
spring.datasource.username=postgres
spring.datasource.password=PostGre@23

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# File upload path
file.upload-dir=src/main/resources/static/uploads/
spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/

# Email config (Gmail example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Port
server.port=8080